### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by ajkblue** [disrvptor/IPMenu#3]
When I try to build the project in Xcode it results in "build succeeded", but fails to actually work, in the Debugger I get these errors (or maybe I'm misunderstanding on how to build this):
![screen shot 2015-10-18 at 1 26 54 pm](https://github-cloud.s3.amazonaws.com/assets/9651939/10566158/39faac1c-759c-11e5-9342-35ef52a902a2.png)

Under Thread 1:

```
#1  0x000000010000a38b in AppDelegate.itemReferencesInLoginItems() -> (existingReference : LSSharedFileListItem?, lastReference : LSSharedFileListItem?) at /Users/ajkblue/Downloads/IPMenu-master/IP Menu/AppDelegate.swift:136
```

Output from Console:

```
Detected new addresses... Regenerating menu
fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb) 
```

**Comment by disrvptor** [comment]
Which version of Xcode are you using? I think some of the stuff I did required Xcode 7.

**Comment by ajkblue** [comment]
I am running Xcode 7.0.1.

**Comment by disrvptor** [comment]
Ok, I see. It looks like `loginItems` can be empty, so unwrapping it's `lastObject` makes no sense. I'll commit a fix and it will be in the next "official" release.
